chore: add time metrics to the exporter
nats-io/prometheus-nats-exporter pull request #265
Opened 2023-11-07 14:46 UTC by ramonberrutti

Parse time metrics as gauge

2023-11-07 19:11 UTC, piotrpio requested changes

2023-11-07 19:11 UTC, piotrpio commented on collector/collector.go
> -	labelKeys := map[string]struct{}{
I'm not sure we want to gather metrics from all keys in `varz`. Other than the time-based metrics you want to add, this would include all the other strings from `Varz` struct, like go version, system account, http_base_path etc. I think we should leave `labelKeys` at they are and just add the required time metrics.

2023-11-07 19:37 UTC, ramonberrutti commented on collector/collector.go
> -	labelKeys := map[string]struct{}{
You are right. I deleted it to test all the metrics and forgot to add it again.

2023-11-08 07:56 UTC, piotrpio approved these changes
LGTM, thanks for the contribution!

2023-11-08 07:56 UTC, merged