Update README.md: add/fix links
nats-io/prometheus-nats-exporter pull request #324
Opened 2024-12-28 01:36 UTC by alexbozhenko

2024-12-28 01:37 UTC, alexbozhenko commented
cc @Jarema

2024-12-30 09:34 UTC, Jarema requested changes
Thanks for the improvement!

Small comments around readibility.

2024-12-30 09:34 UTC, Jarema commented on README.md
> +The exporter aggregates metrics from the server [monitoring endpoints](https://docs.nats.io/running-a-nats-service/nats_admin/monitoring#monitoring-endpoints) you choose (varz, connz, subz,
```suggestion
The exporter aggregates metrics from the NATS server server [monitoring endpoints](https://docs.nats.io/running-a-nats-service/nats_admin/monitoring#monitoring-endpoints) you choose (varz, connz, subz,
```

2024-12-30 09:34 UTC, Jarema commented on README.md
> +routez, healthz...) from a NATS server into a single Prometheus exporter endpoint.
```suggestion
routez, healthz...) into a single Prometheus exporter endpoint.
```

2025-01-06 10:17 UTC, Jarema approved these changes
LGTM

2025-01-06 10:17 UTC, merged